{
    'name': 'E-Learning Courses',
    'version': '14.0.1.0.0',
    'summary': """E-Learning Courses""",
    'description': 'E-Learning Courses',
    'category': 'E-Learning',
    'author': 'LightyD',
    'company': 'LightyD',
    'maintainer': 'LightyD',
    'website': "",
    'depends': ['base', 'contacts', 'website'],
    'data': [
        'security/ir.model.access.csv',
        'views/el_courses_view.xml',
        'views/el_course_lesson_view.xml',
        'views/res_partner_view.xml',
        'views/el_course_room_view.xml',
        'views/el_report_view.xml',
    ],
    'demo': [],
    'images': [],
    'license': 'AGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}
